[profile.release]
panic = 'unwind'

[workspace]
members = [
    'common',
    'executor',
    'node',
    'pallets/nfts',
    'pallets/marketplace',
    'pallets/timed-escrow',
    'primitives',
    'runtime',
]
